import React from 'react';
export const SUPPORTED_LOCALES=['es','en','pt','fr','no'];
export const LOCALE_LABELS={es:'ES',en:'EN',pt:'PT',fr:'FR',no:'NO'};
const KEY='trp.locale';
const messages={
 es:{loading:'Cargando plataforma...',retry:'Reintentar',logout:'Cerrar sesión',language:'Idioma',temporaryBusy:'Servicio temporalmente saturado',nav:{today:'Hoy',business:'Negocio',operation:'Operación',orders:'Órdenes',assets:'Activos',onboarding:'Onboarding',offboarding:'Offboarding',enterpriseControl:'Control Enterprise',agenda:'Agenda',checkout:'Caja y Cobros',quotes:'Cotizaciones',warranties:'Garantías',customers:'Clientes',inventory:'Inventario',settings:'Configuración',overview:'Resumen',organizations:'Organizaciones',commercial:'Comercial y planes',health:'Estado de plataforma',audit:'Auditoría',pilot:'Control de piloto',adminReset:'Restablecimiento admin'},cat:{business:'Negocio',workshop:'Taller',sales:'Clientes y ventas',settings:'Configuración',platform:'Plataforma',control:'Control',sensitive:'Sensible'},status:{pending:'Pendiente',active:'Activo',closed:'Cerrado',cancelled:'Cancelado',confirmed:'Confirmado',notApplicable:'No aplica',suspended:'Suspendido',invited:'Invitado'}},
 en:{loading:'Loading platform...',retry:'Retry',logout:'Sign out',language:'Language',temporaryBusy:'Service temporarily busy',nav:{today:'Today',business:'Business',operation:'Operations',orders:'Work orders',assets:'Assets',onboarding:'Onboarding',offboarding:'Offboarding',enterpriseControl:'Enterprise Control',agenda:'Schedule',checkout:'Checkout & Collections',quotes:'Quotes',warranties:'Warranties',customers:'Customers',inventory:'Inventory',settings:'Settings',overview:'Overview',organizations:'Organizations',commercial:'Commercial & Plans',health:'Platform Health',audit:'Audit',pilot:'Pilot Control',adminReset:'Admin Reset'},cat:{business:'Business',workshop:'Workshop',sales:'Customers & Sales',settings:'Settings',platform:'Platform',control:'Control',sensitive:'Sensitive'},status:{pending:'Pending',active:'Active',closed:'Closed',cancelled:'Cancelled',confirmed:'Confirmed',notApplicable:'Not applicable',suspended:'Suspended',invited:'Invited'}},
 pt:{loading:'Carregando plataforma...',retry:'Tentar novamente',logout:'Sair',language:'Idioma',temporaryBusy:'Serviço temporariamente sobrecarregado',nav:{today:'Hoje',business:'Negócio',operation:'Operação',orders:'Ordens',assets:'Ativos',onboarding:'Onboarding',offboarding:'Offboarding',enterpriseControl:'Controle Enterprise',agenda:'Agenda',checkout:'Caixa e cobranças',quotes:'Cotações',warranties:'Garantias',customers:'Clientes',inventory:'Inventário',settings:'Configurações',overview:'Resumo',organizations:'Organizações',commercial:'Comercial e planos',health:'Estado da plataforma',audit:'Auditoria',pilot:'Controle do piloto',adminReset:'Redefinição admin'},cat:{business:'Negócio',workshop:'Oficina',sales:'Clientes e vendas',settings:'Configurações',platform:'Plataforma',control:'Controle',sensitive:'Sensível'},status:{pending:'Pendente',active:'Ativo',closed:'Fechado',cancelled:'Cancelado',confirmed:'Confirmado',notApplicable:'Não se aplica',suspended:'Suspenso',invited:'Convidado'}},
 fr:{loading:'Chargement de la plateforme...',retry:'Réessayer',logout:'Se déconnecter',language:'Langue',temporaryBusy:'Service temporairement saturé',nav:{today:"Aujourd’hui",business:'Activité',operation:'Opérations',orders:'Ordres de travail',assets:'Actifs',onboarding:'Onboarding',offboarding:'Offboarding',enterpriseControl:'Contrôle Enterprise',agenda:'Agenda',checkout:'Caisse et encaissements',quotes:'Devis',warranties:'Garanties',customers:'Clients',inventory:'Inventaire',settings:'Paramètres',overview:'Vue d’ensemble',organizations:'Organisations',commercial:'Commercial et offres',health:'État de la plateforme',audit:'Audit',pilot:'Contrôle pilote',adminReset:'Réinitialisation admin'},cat:{business:'Activité',workshop:'Atelier',sales:'Clients et ventes',settings:'Paramètres',platform:'Plateforme',control:'Contrôle',sensitive:'Sensible'},status:{pending:'En attente',active:'Actif',closed:'Fermé',cancelled:'Annulé',confirmed:'Confirmé',notApplicable:'Non applicable',suspended:'Suspendu',invited:'Invité'}},
 no:{loading:'Laster plattform...',retry:'Prøv igjen',logout:'Logg ut',language:'Språk',temporaryBusy:'Tjenesten er midlertidig belastet',nav:{today:'I dag',business:'Virksomhet',operation:'Drift',orders:'Arbeidsordrer',assets:'Eiendeler',onboarding:'Onboarding',offboarding:'Offboarding',enterpriseControl:'Enterprise-kontroll',agenda:'Plan',checkout:'Kasse og innbetalinger',quotes:'Tilbud',warranties:'Garantier',customers:'Kunder',inventory:'Lager',settings:'Innstillinger',overview:'Oversikt',organizations:'Organisasjoner',commercial:'Kommersielt og planer',health:'Plattformstatus',audit:'Revisjon',pilot:'Pilotkontroll',adminReset:'Admin-tilbakestilling'},cat:{business:'Virksomhet',workshop:'Verksted',sales:'Kunder og salg',settings:'Innstillinger',platform:'Plattform',control:'Kontroll',sensitive:'Sensitivt'},status:{pending:'Venter',active:'Aktiv',closed:'Lukket',cancelled:'Avbrutt',confirmed:'Bekreftet',notApplicable:'Ikke relevant',suspended:'Suspendert',invited:'Invitert'}}
}
const Context=React.createContext(null);
function initial(){if(typeof window==='undefined')return'es';const saved=localStorage.getItem(KEY);if(SUPPORTED_LOCALES.includes(saved))return saved;const browser=(navigator.language||'es').toLowerCase();const candidate=browser.startsWith('nb')||browser.startsWith('nn')?'no':browser.slice(0,2);return SUPPORTED_LOCALES.includes(candidate)?candidate:'es'}
export function I18nProvider({children}){const[locale,setState]=React.useState(initial);const setLocale=React.useCallback(next=>{if(!SUPPORTED_LOCALES.includes(next))return;setState(next);try{localStorage.setItem(KEY,next)}catch{}},[]);React.useEffect(()=>{document.documentElement.lang=locale},[locale]);const t=React.useCallback((key,fallback)=>{const get=(obj,path)=>path.split('.').reduce((v,k)=>v?.[k],obj);return get(messages[locale],key)??get(messages.es,key)??fallback??key},[locale]);return <Context.Provider value={{locale,setLocale,t}}>{children}</Context.Provider>}
export function useI18n(){const value=React.useContext(Context);return value||{locale:'es',setLocale:()=>{},t:(k,f)=>messages.es[k]??f??k}}
