import {useI18n} from '@/i18n';import {intlLocale} from '@/i18n/format';import React from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { manageEnterpriseOffboarding } from '@/api/enterpriseOffboarding';
import { useAuthContext } from '@/components/contexts/AuthContext';
import PageGuard from '@/components/guards/PageGuard';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useToast } from '@/components/ui/use-toast';
import { Plus, Laptop, KeyRound, CheckCircle2, AlertTriangle } from 'lucide-react';

const formatDate = (value,locale) => value ? new Intl.DateTimeFormat(intlLocale(locale),{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : 'No definido';
export default function EnterpriseOffboarding(){ return <PageGuard allowedRoles={['ORG_ADMIN','BRANCH_ADMIN']} requiredAnyCapabilities={['ENTERPRISE_OFFBOARDING']}><OffboardingContent/></PageGuard>; }
function OffboardingContent(){
 const {locale}=useI18n(); const {effectiveOrgId}=useAuthContext(); const qc=useQueryClient(); const {toast}=useToast();
 const [createOpen,setCreateOpen]=React.useState(false); const [selected,setSelected]=React.useState(null); const [busy,setBusy]=React.useState(false);
 const [form,setForm]=React.useState({name:'',email:'',zeroTime:'',notes:'',systems:'Correo corporativo\nDirectorio / SSO\nVPN\nAplicaciones de negocio'});
 const {data:cases=[]}=useQuery({queryKey:['enterprise-offboarding',effectiveOrgId],queryFn:()=>base44.entities.EnterpriseOffboarding.filter({organization_id:effectiveOrgId},'-opened_at',200),enabled:!!effectiveOrgId});
 const {data:assignments=[]}=useQuery({queryKey:['enterprise-offboarding-assets',effectiveOrgId],queryFn:()=>base44.entities.AssetAssignment.filter({organization_id:effectiveOrgId,status:'ACTIVE'},'-assigned_at',500),enabled:!!effectiveOrgId});
 const {data:access=[]}=useQuery({queryKey:['enterprise-offboarding-access',effectiveOrgId],queryFn:()=>base44.entities.OffboardingAccessItem.filter({organization_id:effectiveOrgId},'-created_date',500),enabled:!!effectiveOrgId});
 const {data:equipment=[]}=useQuery({queryKey:['enterprise-offboarding-equipment',effectiveOrgId],queryFn:()=>base44.entities.Equipo.filter({organization_id:effectiveOrgId}),enabled:!!effectiveOrgId});
 const equipmentById=React.useMemo(()=>Object.fromEntries(equipment.map(e=>[e.id,e])),[equipment]);
 const assetsFor=c=>assignments.filter(a=>(c.subject_reference&&a.assignee_reference===c.subject_reference)||(c.subject_email&&a.assignee_email?.toLowerCase()===c.subject_email.toLowerCase())||(!c.subject_reference&&!c.subject_email&&a.assignee_name===c.subject_name));
 const accessFor=c=>access.filter(a=>a.offboarding_id===c.id); const pendingFor=c=>accessFor(c).filter(a=>a.status==='PENDING'); const openCases=cases.filter(c=>!['CLOSED','CANCELLED'].includes(c.status));
 const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:['enterprise-offboarding',effectiveOrgId]}),qc.invalidateQueries({queryKey:['enterprise-offboarding-access',effectiveOrgId]}),qc.invalidateQueries({queryKey:['enterprise-offboarding-assets',effectiveOrgId]})]);
 async function createCase(){if(!form.name.trim()){toast({variant:'destructive',title:'Indica la persona'});return;}setBusy(true);try{await manageEnterpriseOffboarding({organization_id:effectiveOrgId,action:'OPEN',operation_key:crypto.randomUUID(),subject_name:form.name.trim(),subject_email:form.email.trim(),zero_time:form.zeroTime?new Date(form.zeroTime).toISOString():null,notes:form.notes,access_items:form.systems.split('\n').map(x=>x.trim()).filter(Boolean).map(system_name=>({system_name}))});await refresh();setCreateOpen(false);setForm({name:'',email:'',zeroTime:'',notes:'',systems:'Correo corporativo\nDirectorio / SSO\nVPN\nAplicaciones de negocio'});toast({title:'Offboarding iniciado'});}catch(e){toast({variant:'destructive',title:'No se pudo iniciar',description:e?.message||'Revisa los datos.'});}finally{setBusy(false)}}
 async function confirmAccess(item,status){try{await manageEnterpriseOffboarding({organization_id:effectiveOrgId,action:'CONFIRM_ACCESS',offboarding_id:selected.id,access_item_id:item.id,status});await refresh();toast({title:'Confirmación registrada'});}catch(e){toast({variant:'destructive',title:'No se pudo registrar',description:e?.message});}}
 async function closeCase(){setBusy(true);try{await manageEnterpriseOffboarding({organization_id:effectiveOrgId,action:'CLOSE',offboarding_id:selected.id});await refresh();setSelected(null);toast({title:'Offboarding cerrado',description:'El expediente quedó cerrado y auditado.'});}catch(e){toast({variant:'destructive',title:'El caso todavía tiene pendientes',description:e?.message});}finally{setBusy(false)}}
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Enterprise · Continuidad y custodia</p><h1 className="text-3xl font-semibold tracking-tight text-slate-950">Offboarding tecnológico</h1><p className="mt-1 text-slate-500">Recupera activos, coordina accesos y conserva evidencia antes de cerrar una salida.</p></div><Button onClick={()=>setCreateOpen(true)}><Plus className="mr-2 h-4 w-4"/>Iniciar offboarding</Button></header>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric value={openCases.length} label="Casos abiertos"/><Metric value={openCases.reduce((n,c)=>n+assetsFor(c).length,0)} label="Activos por recuperar"/><Metric value={openCases.reduce((n,c)=>n+pendingFor(c).length,0)} label="Accesos por confirmar"/><Metric value={cases.filter(c=>c.status==='CLOSED').length} label="Casos cerrados"/></div>
 {openCases.length===0?<Card className="border-dashed"><CardContent className="py-14 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-slate-300"/><h3 className="mt-3 font-semibold">Sin salidas abiertas</h3><p className="mt-1 text-sm text-slate-500">Inicia un caso cuando debas recuperar activos y coordinar accesos.</p></CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{openCases.map(c=>{const assets=assetsFor(c),pending=pendingFor(c);return <Card key={c.id} className="border-slate-200"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-950">{c.subject_name}</h3><p className="text-sm text-slate-500">{c.subject_email||'Sin correo'} · Minuto Cero: {formatDate(c.zero_time,locale)}</p></div><Badge className={assets.length||pending.length?'border-0 bg-amber-100 text-amber-800':'border-0 bg-emerald-100 text-emerald-800'}>{assets.length||pending.length?'Con pendientes':'Listo para cerrar'}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3"><Summary icon={Laptop} label="Activos pendientes" value={assets.length}/><Summary icon={KeyRound} label="Accesos pendientes" value={pending.length}/></div><Button className="mt-4 w-full" variant="outline" onClick={()=>setSelected(c)}>Abrir expediente</Button></CardContent></Card>})}</div>}
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Iniciar offboarding tecnológico</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Persona *"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Correo corporativo"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><Field label="Minuto Cero"><Input type="datetime-local" value={form.zeroTime} onChange={e=>setForm({...form,zeroTime:e.target.value})}/><p className="mt-1 text-xs text-slate-500">Momento efectivo desde el que comienza la coordinación tecnológica.</p></Field><Field label="Sistemas y accesos a confirmar"><Textarea className="min-h-28" value={form.systems} onChange={e=>setForm({...form,systems:e.target.value})}/><p className="mt-1 text-xs text-slate-500">Uno por línea. TRP registra coordinación y confirmación; no afirma revocarlos automáticamente.</p></Field><Field label="Notas"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setCreateOpen(false)}>Cancelar</Button><Button disabled={busy} onClick={createCase}>{busy?'Creando…':'Iniciar caso'}</Button></div></div></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Expediente de salida · {selected?.subject_name}</DialogTitle></DialogHeader>{selected&&<div className="space-y-5"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Minuto Cero</p><p className="font-semibold">{formatDate(selected.zero_time,locale)}</p></div><section><h4 className="flex items-center gap-2 font-semibold"><Laptop className="h-4 w-4"/>Activos por recuperar</h4><div className="mt-2 space-y-2">{assetsFor(selected).map(a=>{const e=equipmentById[a.equipo_id]||{};return <div key={a.id} className="rounded-lg border p-3"><p className="text-sm font-medium">{[e.marca,e.modelo].filter(Boolean).join(' ')||e.tipo||'Activo'}</p><p className="text-xs text-slate-500">{e.serie?`Serie ${e.serie}`:'Sin serie'} · registra la devolución desde el expediente del activo.</p></div>})}{assetsFor(selected).length===0&&<p className="flex gap-2 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Sin activos pendientes.</p>}</div></section><section><h4 className="flex items-center gap-2 font-semibold"><KeyRound className="h-4 w-4"/>Accesos y coordinación</h4><div className="mt-2 space-y-2">{accessFor(selected).map(item=><div key={item.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{item.system_name}</p><p className="text-xs text-slate-500">{item.status==='PENDING'?'Pendiente de confirmación':item.status==='CONFIRMED'?'Confirmado':'No aplica'}</p></div>{item.status==='PENDING'&&<div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>confirmAccess(item,'NOT_APPLICABLE')}>No aplica</Button><Button size="sm" onClick={()=>confirmAccess(item,'CONFIRMED')}>Confirmar</Button></div>}</div>)}</div></section>{assetsFor(selected).length===0&&pendingFor(selected).length===0?<Button className="w-full" disabled={busy} onClick={closeCase}><CheckCircle2 className="mr-2 h-4 w-4"/>Cerrar offboarding</Button>:<div className="flex gap-2 rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>No se puede cerrar hasta recuperar activos y resolver accesos.</div>}</div>}</DialogContent></Dialog></div>;
}
function Metric({value,label}){return <Card className="border-slate-200"><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-slate-500">{label}</p></CardContent></Card>}
function Summary({icon:Icon,label,value}){return <div className="rounded-xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-slate-400"/><p className="mt-2 text-xs text-slate-400">{label}</p><p className="font-semibold">{value}</p></div>}
function Field({label,children}){return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>}
