import {useI18n} from '@/i18n';import {intlLocale} from '@/i18n/format';import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useAuthContext } from '@/components/contexts/AuthContext';
import PageGuard from '@/components/guards/PageGuard';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ShieldCheck, Laptop, UserPlus, UserMinus, KeyRound, AlertTriangle, ArrowRight, Clock3, FileCheck2 } from 'lucide-react';
const d=(v,locale)=>v?new Intl.DateTimeFormat(intlLocale(locale),{dateStyle:'medium'}).format(new Date(v)):'—';
export default function EnterpriseCommand(){return <PageGuard allowedRoles={['ORG_ADMIN','BRANCH_ADMIN']} requiredAnyCapabilities={['ENTERPRISE_COMMAND_EVIDENCE']}><Content/></PageGuard>}
function Content(){const {locale,t}=useI18n();const {effectiveOrgId}=useAuthContext(),navigate=useNavigate();
 const {data:assignments=[]}=useQuery({queryKey:['enterprise-command-assignments',effectiveOrgId],queryFn:()=>base44.entities.AssetAssignment.filter({organization_id:effectiveOrgId},'-assigned_at',500),enabled:!!effectiveOrgId});
 const {data:onboarding=[]}=useQuery({queryKey:['enterprise-command-onboarding',effectiveOrgId],queryFn:()=>base44.entities.EnterpriseOnboarding.filter({organization_id:effectiveOrgId},'-opened_at',300),enabled:!!effectiveOrgId});const {data:onboardingAccess=[]}=useQuery({queryKey:['enterprise-command-onboarding-access',effectiveOrgId],queryFn:()=>base44.entities.OnboardingAccessItem.filter({organization_id:effectiveOrgId},'-created_date',500),enabled:!!effectiveOrgId});
 const {data:cases=[]}=useQuery({queryKey:['enterprise-command-offboarding',effectiveOrgId],queryFn:()=>base44.entities.EnterpriseOffboarding.filter({organization_id:effectiveOrgId},'-opened_at',300),enabled:!!effectiveOrgId});
 const {data:access=[]}=useQuery({queryKey:['enterprise-command-access',effectiveOrgId],queryFn:()=>base44.entities.OffboardingAccessItem.filter({organization_id:effectiveOrgId},'-created_date',500),enabled:!!effectiveOrgId});
 const {data:equipment=[]}=useQuery({queryKey:['enterprise-command-equipment',effectiveOrgId],queryFn:()=>base44.entities.Equipo.filter({organization_id:effectiveOrgId}),enabled:!!effectiveOrgId});
 const eq=React.useMemo(()=>Object.fromEntries(equipment.map(x=>[x.id,x])),[equipment]);const activeAssignments=assignments.filter(a=>a.status==='ACTIVE');const overdue=activeAssignments.filter(a=>a.expected_return_at&&new Date(a.expected_return_at)<new Date());const openCases=cases.filter(c=>!['CLOSED','CANCELLED'].includes(c.status));const openOnboarding=onboarding.filter(c=>c.status==='OPEN');const pendingOnboardingAccess=onboardingAccess.filter(a=>a.status==='PENDING'&&openOnboarding.some(c=>c.id===a.onboarding_id));const pendingAccess=access.filter(a=>a.status==='PENDING'&&openCases.some(c=>c.id===a.offboarding_id));const closed=cases.filter(c=>c.status==='CLOSED');
 const exceptions=[...openOnboarding.filter(c=>pendingOnboardingAccess.some(a=>a.onboarding_id===c.id)).map(c=>({type:'Preparación pendiente',title:c.subject_name,detail:`${pendingOnboardingAccess.filter(a=>a.onboarding_id===c.id).length} acceso(s) por preparar`,date:c.start_at,target:'/EnterpriseOnboarding'})),...overdue.map(a=>({type:'Devolución vencida',title:a.assignee_name,detail:[eq[a.equipo_id]?.marca,eq[a.equipo_id]?.modelo,eq[a.equipo_id]?.serie].filter(Boolean).join(' · ')||'Activo',date:a.expected_return_at,target:'/Activos'})),...openCases.flatMap(c=>{const pa=pendingAccess.filter(x=>x.offboarding_id===c.id);return pa.length?[{type:'Accesos pendientes',title:c.subject_name,detail:`${pa.length} confirmación${pa.length===1?'':'es'} pendiente${pa.length===1?'':'s'}`,date:c.zero_time,target:'/EnterpriseOffboarding'}]:[]})];
 return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Enterprise · Command & Evidence</p><h1 className="text-3xl font-semibold tracking-tight text-slate-950">Control empresarial</h1><p className="mt-1 text-slate-500">Custodia, salidas tecnológicas, pendientes y evidencia en una sola vista.</p></header><div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric icon={UserPlus} n={openOnboarding.length} t="Onboardings abiertos"/><Metric icon={Laptop} n={activeAssignments.length} t="Activos en custodia"/><Metric icon={AlertTriangle} n={overdue.length} t="Devoluciones vencidas" warn={overdue.length>0}/><Metric icon={UserMinus} n={openCases.length} t="Offboardings abiertos"/><Metric icon={KeyRound} n={pendingAccess.length} t="Accesos pendientes" warn={pendingAccess.length>0}/><Metric icon={FileCheck2} n={closed.length} t="Expedientes cerrados"/></div>
 <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Card className="border-slate-200"><CardContent className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-lg">Atención requerida</h2><p className="text-sm text-slate-500">Excepciones que impiden una operación limpia.</p></div><Badge variant="outline">{exceptions.length}</Badge></div><div className="mt-4 space-y-2">{exceptions.map((x,i)=><button key={`${x.type}-${i}`} onClick={()=>navigate(x.target)} className="flex w-full items-center justify-between gap-3 rounded-xl border p-4 text-left hover:bg-slate-50"><div><div className="flex items-center gap-2"><Badge className="border-0 bg-amber-100 text-amber-800">{x.type}</Badge><span className="font-medium">{x.title}</span></div><p className="mt-1 text-sm text-slate-500">{x.detail} · {d(x.date,locale)}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-slate-400"/></button>)}{exceptions.length===0&&<div className="py-10 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-emerald-500"/><p className="mt-2 font-medium">Sin excepciones abiertas</p><p className="text-sm text-slate-500">No hay devoluciones vencidas ni accesos pendientes.</p></div>}</div></CardContent></Card>
 <Card className="border-slate-200"><CardContent className="p-5"><h2 className="font-semibold text-lg">Evidencia operativa</h2><p className="text-sm text-slate-500">Señales verificables conservadas por TRP.</p><div className="mt-4 space-y-3"><Evidence label="Asignaciones registradas" value={assignments.length}/><Evidence label="Devoluciones documentadas" value={assignments.filter(a=>a.status==='RETURNED').length}/><Evidence label="Confirmaciones de acceso" value={access.filter(a=>a.status==='CONFIRMED').length}/><Evidence label="Casos cerrados" value={closed.length}/></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs text-slate-600"><Clock3 className="mb-2 h-4 w-4"/>La evidencia muestra lo registrado y confirmado dentro de TRP. No sustituye evidencia de sistemas externos que no estén integrados.</div></CardContent></Card></div>
 <div className="grid gap-4 md:grid-cols-3"><Button variant="outline" className="h-auto justify-between p-5" onClick={()=>navigate('/EnterpriseOnboarding')}><span className="text-left"><span className="block font-semibold">{t('finalI18n.onboardingTech','Onboarding tecnológico')}</span><span className="block text-xs text-slate-500">Preparación de accesos e ingreso.</span></span><ArrowRight className="h-4 w-4"/></Button><Button variant="outline" className="h-auto justify-between p-5" onClick={()=>navigate('/Activos')}><span className="text-left"><span className="block font-semibold">{t('finalI18n.assetCustody','Custodia de activos')}</span><span className="block text-xs text-slate-500">Responsables, devoluciones e historial.</span></span><ArrowRight className="h-4 w-4"/></Button><Button variant="outline" className="h-auto justify-between p-5" onClick={()=>navigate('/EnterpriseOffboarding')}><span className="text-left"><span className="block font-semibold">{t('finalI18n.offboardingTech','Offboarding tecnológico')}</span><span className="block text-xs text-slate-500">Minuto Cero, activos y accesos.</span></span><ArrowRight className="h-4 w-4"/></Button></div></div>}
function Metric({icon:Icon,n,t,warn}){return <Card className={warn?'border-amber-200 bg-amber-50':'border-slate-200'}><CardContent className="p-4"><Icon className="h-4 w-4 text-slate-400"/><p className="mt-2 text-2xl font-bold">{n}</p><p className="text-xs text-slate-500">{t}</p></CardContent></Card>};function Evidence({label,value}){return <div className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span className="text-slate-600">{label}</span><strong>{value}</strong></div>}
